apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: tpod-proxy-policy  
spec:
  images:
    - glob: {{.Values.policy.imageGlob|quote}}
  authorities:
    {{ if .Values.policy.issuer }}
    - keyless:
        identities:
          - issuer: {{ .Values.policy.issuer | quote }}  
            subject: {{ .Values.policy.subject | quote }} 
    {{ end }}
    {{ if .Values.policy.key }}
    - key:
        data: |{{ .Values.policy.key | nindent 10 }}
    {{ end }}

