#!/command/with-contenv sh

set -e

. /shared_secrets/backend_key.env
. /secrets/backend.env

apocryph-s3-backend \
    --bind 127.0.0.1:8593 \
    --minio 127.0.0.1:9000 \
    --ethereum "$BACKEND_ETH_RPC" \
    --prometheus http://127.0.0.1:9090/ \
    --token-contract "$BACKEND_ETH_TOKEN" \
    --withdraw-address "$BACKEND_ETH_WITHDRAW" \
    --chain-id "$BACKEND_ETH_CHAIN_ID" \
    --external-url "$BACKEND_EXTERNAL_URL" \
    --replicate-sites "$BACKEND_REPLICATE_SITES"
