{{ if .Values.minio.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-backend
  template:
    metadata:
      labels:
        app: s3-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        args: [
          "--bind", ":8593",
          "--minio", "minio.{{ .Release.Namespace }}.svc.cluster.local:80",
          "--ethereum", "{{.Values.eth.rpc}}",
          "--prometheus", "http://prometheus.{{ .Release.Namespace }}.svc.cluster.local:80/",
          "--token-contract", "{{ .Values.eth.tokenContract }}",
          "--withdraw-address", "{{ .Values.eth.withdrawAddress }}",
          "--chain-id", "{{ .Values.eth.chainId }}",
          "--private-key", "{{ .Values.eth.privateKey }}",
          {{ if .Values.serf.enable }}
          "--serf", "serf-rpc.{{ .Release.Namespace }}.svc.cluster.local:7373",
          "--hostname", "aapp-nginx.{{ .Release.Namespace }}.svc.cluster.local",
          {{ else }}
          "--disable-replication",
          {{ end }}
        ]
        ports:
        - containerPort: 8593
        volumeMounts:
        - name: access-secret
          mountPath: /.env
          subPath: .env
          readOnly: true
      volumes:
      - name: access-secret
        secret:
          secretName: backend-access-secret
---
apiVersion: v1
kind: Service
metadata:
  name: policy-backend
spec:
  selector:
    app: s3-backend
  ports:
  - name: minio-auth
    port: 8593
{{ end }}
