{{ if .Values.minio.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: aapp-nginx-config
data:
  apocryphLogin.html: |-{{ tpl (.Files.Get "files/apocryphLogin.html") . | nindent 4 }}
  nginx.conf: |-{{ tpl (.Files.Get "files/nginx.conf") . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aapp-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aapp-nginx
  template:
    metadata:
      labels:
        app: aapp-nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        volumeMounts:
        - name: configs
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          readOnly: true
        - name: htmls
          mountPath: /usr/share/nginx/html/x/
          readOnly: true
        ports:
        - containerPort: 80
      volumes:
      - name: configs
        configMap:
          name: aapp-nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: htmls
        configMap:
          name: aapp-nginx-config
          items:
          - key: apocryphLogin.html
            path: apocryphLogin/index.html
---
apiVersion: v1
kind: Service
metadata:
  name: aapp-nginx
spec:
  selector:
    app: aapp-nginx
  ports:
  - name: http
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3-nginx-ingress
spec:
  rules:
  - host: "*.{{ .Values.nginx.globalHostConsole }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aapp-nginx
            port:
              number: 80
  - host: "*.{{ .Values.nginx.globalHost }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aapp-nginx
            port:
              number: 80
{{ end }}
