apiVersion: v1
kind: Secret
metadata:
  name: minio-config
data:
  config.env: {{ tpl (.Files.Get "files/minio.env") . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-access-secret
data:
  '.env': {{ tpl (.Files.Get "files/backend.env") . | b64enc }}
