package constants

const PRIVATE_KEY = "PRIVATE_KEY"
const PUBLIC_ADDRESS_KEY = "PUBLIC_ADDRESS"
const PAYMENT_ADDR_KEY = "PAYMENT_ADDRESS"
const PUBLISHER_ADDR_KEY = "PUBLISHER_ADDRESS"
const PROVIDER_ADDR_KEY = "PROVIDER_ADDRESS"
const POD_ID_KEY = "POD_ID"

const OUTPUT_SIGNATURE_PATH = "~/.apocryph/signatures/"

const ReservedTpodProxyPort int32 = 63917
