name: Run tests and check format

on: [push, pull_request]

jobs:
  dotnet-test:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet build
    - run: dotnet test --blame-hang --blame-hang-timeout 20s
      timeout-minutes: 10
  dotnet-format:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet tool install --global dotnet-format --version 5.0
    - run: dotnet restore
    - run: ~/.dotnet/tools/dotnet-format --fix-style warn --fix-whitespace --check
